// ─── Geography.js (v28.141) ────────────────────────────────────────────────
// Shared US state + Texas/New Mexico county data. Born as NewJobConstants.js
// (v28.94, ship 1 of the NewWorkOrderModal split); renamed to this neutral name in
// v28.141 when the EditWorkOrderModal split needed the same tables — the exact
// "another surface needs counties or state codes" case the v28.94 header
// anticipated. Imported by the NewJob flow (NewWorkOrderLocationPanel, useNewWorkOrderForm)
// and by EditWorkOrderModal.
//
// TX_COUNTIES — the 113-county Texas list historically appearing on Flo-Test
// work orders (the company is Permian-Basin-centered but covers the state).
// NM_COUNTIES — New Mexico county list (30 entries; see note). VALID_STATES —
// the 50-state + DC two-letter codes used by the state-input validator and
// the pin-resolve geocoder. ALL_COUNTIES — TX+NM merged and pre-sorted at
// module load so the County autocomplete doesn't re-sort per render.
//
// Note on NM_COUNTIES: 30 of 33 entries listed historically. The gaps
// predate the v28.94 extraction and are preserved verbatim — a job in a
// missing county just misses the autocomplete suggestion (non-blocking).

const TX_COUNTIES = [
  "Andrews",
  "Archer",
  "Armstrong",
  "Bailey",
  "Baylor",
  "Borden",
  "Brewster",
  "Briscoe",
  "Brooks",
  "Brown",
  "Callahan",
  "Carson",
  "Castro",
  "Childress",
  "Clay",
  "Cochran",
  "Coke",
  "Coleman",
  "Collingsworth",
  "Comanche",
  "Concho",
  "Cottle",
  "Crane",
  "Crockett",
  "Crosby",
  "Culberson",
  "Dallam",
  "Dawson",
  "Deaf Smith",
  "Dickens",
  "Dimmit",
  "Donley",
  "Eastland",
  "Ector",
  "Edwards",
  "El Paso",
  "Fisher",
  "Floyd",
  "Foard",
  "Gaines",
  "Garza",
  "Glasscock",
  "Gray",
  "Hale",
  "Hall",
  "Hansford",
  "Hardeman",
  "Hartley",
  "Haskell",
  "Hemphill",
  "Howard",
  "Hudspeth",
  "Hutchinson",
  "Irion",
  "Jeff Davis",
  "Jones",
  "Kent",
  "Kimble",
  "King",
  "Kinney",
  "Knox",
  "Lamb",
  "Lampasas",
  "Lipscomb",
  "Llano",
  "Loving",
  "Lubbock",
  "Lynn",
  "Martin",
  "Mason",
  "Maverick",
  "McCulloch",
  "McMullen",
  "Menard",
  "Midland",
  "Mills",
  "Mitchell",
  "Montague",
  "Moore",
  "Motley",
  "Nolan",
  "Ochiltree",
  "Oldham",
  "Palo Pinto",
  "Parmer",
  "Pecos",
  "Potter",
  "Presidio",
  "Randall",
  "Reagan",
  "Real",
  "Reeves",
  "Roberts",
  "Runnels",
  "San Saba",
  "Schleicher",
  "Scurry",
  "Shackelford",
  "Sherman",
  "Stephens",
  "Sterling",
  "Stonewall",
  "Sutton",
  "Swisher",
  "Taylor",
  "Terrell",
  "Terry",
  "Throckmorton",
  "Tom Green",
  "Upton",
  "Uvalde",
  "Val Verde",
  "Ward",
  "Wheeler",
  "Winkler",
  "Yoakum",
  "Young",
  "Zavala",
];

const NM_COUNTIES = [
  "Chaves",
  "Cibola",
  "Curry",
  "De Baca",
  "Dona Ana",
  "Eddy",
  "Grant",
  "Guadalupe",
  "Harding",
  "Hidalgo",
  "Lea",
  "Lincoln",
  "Los Alamos",
  "Luna",
  "McKinley",
  "Mora",
  "Otero",
  "Quay",
  "Rio Arriba",
  "Roosevelt",
  "San Juan",
  "San Miguel",
  "Sandoval",
  "Santa Fe",
  "Sierra",
  "Socorro",
  "Taos",
  "Torrance",
  "Union",
  "Valencia",
];

// Pre-sorted merge — was sorted in the render path before v28.94. Sort
// once at module load instead.
export const ALL_COUNTIES = [...TX_COUNTIES, ...NM_COUNTIES].sort();

export const VALID_STATES = [
  "AL",
  "AK",
  "AZ",
  "AR",
  "CA",
  "CO",
  "CT",
  "DE",
  "FL",
  "GA",
  "HI",
  "ID",
  "IL",
  "IN",
  "IA",
  "KS",
  "KY",
  "LA",
  "ME",
  "MD",
  "MA",
  "MI",
  "MN",
  "MS",
  "MO",
  "MT",
  "NE",
  "NV",
  "NH",
  "NJ",
  "NM",
  "NY",
  "NC",
  "ND",
  "OH",
  "OK",
  "OR",
  "PA",
  "RI",
  "SC",
  "SD",
  "TN",
  "TX",
  "UT",
  "VT",
  "VA",
  "WA",
  "WV",
  "WI",
  "WY",
  "DC",
];
