// ─── NewJobConstants (v28.94 — ship 1 of NewJobModal split) ────────────────
// Pure-data tables lifted out of NewJobModal.jsx so the modal file can
// focus on flow + JSX instead of paging past 165 lines of state/county
// literals.
//
// Source of truth — TX_COUNTIES is the 113-county list of Texas counties
// historically appearing on Flo-Test work orders (the company operates
// primarily in the Permian Basin but covers the full state). NM_COUNTIES
// is New Mexico's full 33 county list (currently 30 entries here — see
// note below). VALID_STATES is the standard 50-state + DC two-letter
// codes used by the state-input validator and pin-resolve geocoder.
//
// `ALL_COUNTIES` is the merged sorted list used by the County
// autocomplete dropdown. Pre-sorted at module load so callers don't
// re-sort on every render (was previously sorted inside the render
// function — small free perf win).
//
// Note on NM_COUNTIES: only 30 of 33 entries listed historically.
// Whatever the gaps are, they predate the v28.94 extraction and are
// preserved verbatim. If a future job lands in a missing county the
// autocomplete will just miss the suggestion and the user types it
// freehand — non-blocking.
//
// Future cleanup candidate (NOT part of this split arc): if another
// surface in the app needs counties or state codes (e.g. a customer-
// address form or a reports filter), promote these to `Geography.js`
// and import from both places. Today there's exactly one caller.

export const TX_COUNTIES = [
  "Andrews",
  "Archer",
  "Armstrong",
  "Bailey",
  "Baylor",
  "Borden",
  "Brewster",
  "Briscoe",
  "Brooks",
  "Brown",
  "Callahan",
  "Carson",
  "Castro",
  "Childress",
  "Clay",
  "Cochran",
  "Coke",
  "Coleman",
  "Collingsworth",
  "Comanche",
  "Concho",
  "Cottle",
  "Crane",
  "Crockett",
  "Crosby",
  "Culberson",
  "Dallam",
  "Dawson",
  "Deaf Smith",
  "Dickens",
  "Dimmit",
  "Donley",
  "Eastland",
  "Ector",
  "Edwards",
  "El Paso",
  "Fisher",
  "Floyd",
  "Foard",
  "Gaines",
  "Garza",
  "Glasscock",
  "Gray",
  "Hale",
  "Hall",
  "Hansford",
  "Hardeman",
  "Hartley",
  "Haskell",
  "Hemphill",
  "Howard",
  "Hudspeth",
  "Hutchinson",
  "Irion",
  "Jeff Davis",
  "Jones",
  "Kent",
  "Kimble",
  "King",
  "Kinney",
  "Knox",
  "Lamb",
  "Lampasas",
  "Lipscomb",
  "Llano",
  "Loving",
  "Lubbock",
  "Lynn",
  "Martin",
  "Mason",
  "Maverick",
  "McCulloch",
  "McMullen",
  "Menard",
  "Midland",
  "Mills",
  "Mitchell",
  "Montague",
  "Moore",
  "Motley",
  "Nolan",
  "Ochiltree",
  "Oldham",
  "Palo Pinto",
  "Parmer",
  "Pecos",
  "Potter",
  "Presidio",
  "Randall",
  "Reagan",
  "Real",
  "Reeves",
  "Roberts",
  "Runnels",
  "San Saba",
  "Schleicher",
  "Scurry",
  "Shackelford",
  "Sherman",
  "Stephens",
  "Sterling",
  "Stonewall",
  "Sutton",
  "Swisher",
  "Taylor",
  "Terrell",
  "Terry",
  "Throckmorton",
  "Tom Green",
  "Upton",
  "Uvalde",
  "Val Verde",
  "Ward",
  "Wheeler",
  "Winkler",
  "Yoakum",
  "Young",
  "Zavala",
];

export const NM_COUNTIES = [
  "Chaves",
  "Cibola",
  "Curry",
  "De Baca",
  "Dona Ana",
  "Eddy",
  "Grant",
  "Guadalupe",
  "Harding",
  "Hidalgo",
  "Lea",
  "Lincoln",
  "Los Alamos",
  "Luna",
  "McKinley",
  "Mora",
  "Otero",
  "Quay",
  "Rio Arriba",
  "Roosevelt",
  "San Juan",
  "San Miguel",
  "Sandoval",
  "Santa Fe",
  "Sierra",
  "Socorro",
  "Taos",
  "Torrance",
  "Union",
  "Valencia",
];

// Pre-sorted merge — was sorted in the render path before v28.94. Sort
// once at module load instead.
export const ALL_COUNTIES = [...TX_COUNTIES, ...NM_COUNTIES].sort();

export const VALID_STATES = [
  "AL",
  "AK",
  "AZ",
  "AR",
  "CA",
  "CO",
  "CT",
  "DE",
  "FL",
  "GA",
  "HI",
  "ID",
  "IL",
  "IN",
  "IA",
  "KS",
  "KY",
  "LA",
  "ME",
  "MD",
  "MA",
  "MI",
  "MN",
  "MS",
  "MO",
  "MT",
  "NE",
  "NV",
  "NH",
  "NJ",
  "NM",
  "NY",
  "NC",
  "ND",
  "OH",
  "OK",
  "OR",
  "PA",
  "RI",
  "SC",
  "SD",
  "TN",
  "TX",
  "UT",
  "VT",
  "VA",
  "WA",
  "WV",
  "WI",
  "WY",
  "DC",
];
